#pragma once
// Generated by source/integrate_fft.py and source/generate_controls.py.
// UI ranges are recommendations; manual entry remains uncapped.
// Uniform names, namespaces, types, defaults and non-layout annotations
// are preserved for existing ReShade presets.

// 01. Sources and colour
uniform int SourceMode < ui_category="01. Sources and colour";  ui_label="Apply to"; ui_type="combo"; ui_items="Detected lights\0Extracted highlights\0Full frame\0"; ui_tooltip="Choose detected point lights, extracted highlights, or the full image as flare sources.";  ui_text="RTLensFlares 1.6.0 | Ray-traced lens ghosts and FFT diffraction"; ui_category_closed=false; > = 1;
namespace FFT {
uniform int InputSpace < ui_category="01. Sources and colour";  ui_label="Input colour space"; ui_tooltip="Colour encoding of the game image. Processing is performed in linear light."; ui_type="combo"; ui_items="sRGB SDR\0Linear / scRGB\0HDR10 PQ\0";  > = 0;
uniform float ReferenceWhite < ui_category="01. Sources and colour";  ui_label="Reference white (nits)"; ui_tooltip="Brightness represented by linear value 1 when reading or writing HDR10, in nits."; ui_type="slider"; ui_min=80; ui_max=1000;  > = 203;
uniform float PreExposure < ui_category="01. Sources and colour";  ui_label="Highlight selection exposure (stops)"; ui_tooltip="Exposure applied before source selection. Positive values include more of the image."; ui_type="slider"; ui_min=-8; ui_max=8;  > = 0;
uniform float SourceExposure < ui_category="01. Sources and colour";  ui_label="Convolution source exposure (stops)"; ui_tooltip="Exposure of the selected sources feeding both ray tracing and FFT bloom."; ui_type="slider"; ui_min=-8; ui_max=8;  > = 0;

// 02. Source contrast and highlights
}
uniform float FullFrameContrast < ui_category="02. Source contrast and highlights";  ui_label="Full-frame contrast"; ui_tooltip="Contrast of full-frame flare sources around the pivot. Above 1 darkens shadows and strengthens highlights."; ui_type="slider"; ui_min=0.25; ui_max=4; ui_category_closed=true; > = 1;
uniform float FullFramePivot < ui_category="02. Source contrast and highlights";  ui_label="Full-frame contrast pivot"; ui_tooltip="Linear-light brightness left unchanged by full-frame contrast."; ui_type="slider"; ui_min=0.01; ui_max=2; > = 0.18;
uniform float FullFrameBlack < ui_category="02. Source contrast and highlights";  ui_label="Full-frame black level"; ui_tooltip="Black level subtracted from full-frame sources before contrast. Removes low-level veiling flare."; ui_type="slider"; ui_min=0; ui_max=0.25; > = 0;
namespace FFT {
uniform float MaximumSource < ui_category="02. Source contrast and highlights";  ui_label="Maximum source"; ui_tooltip="Maximum source-channel value before thresholding. Reduces the influence of extreme highlights."; ui_type="slider"; ui_min=1; ui_max=1024;  > = 64;
uniform float HighlightCompression < ui_category="02. Source contrast and highlights";  ui_label="Highlight shoulder"; ui_tooltip="Compress bright source values with a soft shoulder. Higher values reduce their relative energy."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float Threshold < ui_category="02. Source contrast and highlights";  ui_label="Threshold"; ui_tooltip="Minimum source brightness for highlight and detected-light modes. Full-frame mode bypasses it."; ui_type="slider"; ui_min=0; ui_max=2;  > = 0.6;
uniform float SoftKnee < ui_category="02. Source contrast and highlights";  ui_label="Soft knee"; ui_tooltip="Softens the transition around the highlight threshold."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0.5;
uniform bool PerChannelThreshold < ui_category="02. Source contrast and highlights";  ui_label="Per-channel threshold"; ui_tooltip="Apply the highlight threshold separately to red, green and blue.";  > = false;
uniform float ThresholdColourPreservation < ui_category="02. Source contrast and highlights";  ui_label="Threshold colour preservation"; ui_tooltip="Restore the source colour after per-channel thresholding. 1 preserves its original channel ratios."; ui_type="slider"; ui_min=0; ui_max=1;  > = 1;
uniform float AntiFirefly < ui_category="02. Source contrast and highlights";  ui_label="Isolated hot-pixel suppression"; ui_tooltip="Reduce isolated bright pixels using the surrounding source brightness."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float TemporalSmoothing < ui_category="02. Source contrast and highlights";  ui_label="Highlight smoothing"; ui_tooltip="Blend source values across frames. Changes in brightness reduce the retained history."; ui_type="slider"; ui_min=0; ui_max=0.9;  > = 0;

// 03. Point-light detection
}
uniform float DetectionMinimum < ui_category="03. Point-light detection";  ui_label="Minimum detected peak"; ui_type="slider"; ui_min=0; ui_max=1; ui_step=0.0001; ui_tooltip="Minimum peak brightness accepted by point-light detection."; ui_category_closed=true; > = 0.001;
uniform float DetectionContrast < ui_category="03. Point-light detection";  ui_label="Light / tile background contrast"; ui_type="slider"; ui_min=1; ui_max=8; ui_step=0.05; ui_tooltip="Required contrast between a detected peak and its tile background."; > = 2;
uniform float DetectionRadius < ui_category="03. Point-light detection";  ui_label="Light cluster radius (source texels)"; ui_type="slider"; ui_min=0; ui_max=16; ui_step=0.1; ui_tooltip="Radius around each detected peak used to collect its position, colour and energy."; > = 5;

// 04. Lens and sensor
uniform int LensIndex < ui_category="04. Lens and sensor";  ui_label="Patent lens"; ui_type="combo"; ui_items=_RTL_LENS_ITEMS; ui_tooltip="Choose an optical design. Lenses are ordered from the shortest focal length to the longest."; ui_category_closed=false; > = _RTL_DEFAULT_MENU;
uniform float ZoomPosition < ui_category="04. Lens and sensor";  ui_label="Zoom position (wide to tele)"; ui_type="slider"; ui_min=0.0; ui_max=1.0; ui_step=0.001; ui_tooltip="Move a zoom lens from its published wide pose at 0 to its telephoto pose at 1. Prime lenses ignore this."; > = 0.0;
uniform float AnamorphicRotation < ui_category="04. Lens and sensor";  ui_label="Anamorphic lens rotation (degrees)"; ui_type="slider"; ui_min=-180; ui_max=180; ui_step=0.1; ui_tooltip="Rotate the ray-traced anamorphic lens around its optical axis."; > = 0;
uniform float LensScale < ui_category="04. Lens and sensor";  ui_label="Prescription scale"; ui_type="slider"; ui_min=0.25; ui_max=4; ui_step=0.01; ui_tooltip="Scale the optical prescription and its focal length. Sensor width stays independent."; > = 1;
uniform float SensorWidth < ui_category="04. Lens and sensor";  ui_label="Sensor width (mm)"; ui_type="slider"; ui_min=8; ui_max=70; ui_step=0.1; ui_tooltip="Sensor width in millimetres. Controls the source angles and the portion of each ghost seen in the image."; > = 36;
uniform float FocusShift < ui_category="04. Lens and sensor";  ui_label="Sensor focus offset (mm)"; ui_type="slider"; ui_min=-10; ui_max=10; ui_step=0.01; ui_tooltip="Move the sensor behind or in front of its nominal focus plane."; > = 0;
uniform float FNumber < ui_category="04. Lens and sensor";  ui_label="F-number (0 = lens nominal)"; ui_type="slider"; ui_min=0; ui_max=22; ui_step=0.1; ui_tooltip="Physical lens aperture. Higher values close the iris; 0 uses the design's nominal f-number."; > = 0;

// 05. Glass, coatings and barrel
uniform float Dispersion < ui_category="05. Glass, coatings and barrel";  ui_label="Glass dispersion multiplier"; ui_type="slider"; ui_min=0; ui_max=3; ui_step=0.01; ui_tooltip="Scale the variation of glass index with wavelength. 0 removes refractive colour separation."; ui_category_closed=true; > = 1;
uniform float Absorption < ui_category="05. Glass, coatings and barrel";  ui_label="Glass absorption per mm"; ui_type="slider"; ui_min=0; ui_max=0.1; ui_step=0.0001; ui_tooltip="Light lost per millimetre travelled through glass. Longer reflection paths lose more energy."; > = 0;
uniform float ClearRadiusScale < ui_category="05. Glass, coatings and barrel";  ui_label="Clear aperture radius scale"; ui_type="slider"; ui_min=0.25; ui_max=2; ui_step=0.01; ui_tooltip="Scale the clear apertures and entrance search domain. Changes clipping and vignetting."; > = 1;
uniform float CoatingMix < ui_category="05. Glass, coatings and barrel";  ui_label="AR-coated fraction"; ui_type="slider"; ui_min=0; ui_max=1; ui_step=0.01; ui_tooltip="Blend bare-glass reflection with the thin-film antireflection coating."; > = 0.9;
uniform float CoatingIndex < ui_category="05. Glass, coatings and barrel";  ui_label="Coating refractive index"; ui_type="slider"; ui_min=1; ui_max=2.5; ui_step=0.001; ui_tooltip="Refractive index of the coating film."; > = 1.38;
uniform float CoatingThickness < ui_category="05. Glass, coatings and barrel";  ui_label="Coating thickness (nm)"; ui_type="slider"; ui_min=0; ui_max=300; ui_step=0.1; ui_tooltip="Film thickness in nanometres. Controls wavelength- and angle-dependent reflection colours."; > = 100;
uniform bool BarrelEnabled < ui_category="05. Glass, coatings and barrel";  ui_label="Trace inner barrel reflections"; ui_tooltip="Trace one specular reflection from the inferred barrel wall in each air gap."; > = false;
uniform float BarrelRadiusScale < ui_category="05. Glass, coatings and barrel";  ui_label="Inner barrel radius scale"; ui_type="slider"; ui_min=0.8; ui_max=3; ui_step=0.01; ui_tooltip="Barrel radius relative to neighbouring clear apertures."; > = 1.05;
uniform float BarrelReflectivity < ui_category="05. Glass, coatings and barrel";  ui_label="Barrel reflectivity at normal incidence"; ui_type="slider"; ui_min=0; ui_max=0.2; ui_step=0.001; ui_tooltip="Wall reflectivity at normal incidence. Reflection increases at grazing angles."; > = 0.02;
uniform float BarrelIntensity < ui_category="05. Glass, coatings and barrel";  ui_label="Barrel reflection intensity"; ui_type="slider"; ui_min=0; ui_max=4; ui_step=0.01; ui_tooltip="Multiply the energy of barrel-reflection paths."; > = 1;
uniform float3 BarrelTint < ui_category="05. Glass, coatings and barrel";  ui_label="Barrel reflection tint"; ui_type="slider"; ui_min=0; ui_max=4; ui_step=0.01; ui_tooltip="Colour multiplier for barrel-reflection paths."; > = float3(1,1,1);

// 06. Shared pupil size and shape
uniform bool LinkFFTIris < ui_category="06. Shared pupil size and shape";  ui_label="Link FFT pupil to lens f-number"; ui_tooltip="Make the FFT pupil shrink as the physical f-number increases."; ui_category_closed=true; > = true;
uniform float FFTIrisReference < ui_category="06. Shared pupil size and shape";  ui_label="FFT pupil reference f-number"; ui_type="slider"; ui_min=0.7; ui_max=16; ui_step=0.01; ui_tooltip="F-number at which the linked FFT pupil uses the specified aperture radius."; > = 1.4;
uniform bool LinkFFTAnamorphic < ui_category="06. Shared pupil size and shape";  ui_label="Link FFT aperture to lens squeeze"; ui_tooltip="Adjust FFT pupil aspect using the selected lens's anamorphic squeeze."; > = false;
namespace FFT {
uniform float ApertureRadius < ui_category="06. Shared pupil size and shape";  ui_label="Aperture radius"; ui_tooltip="Radius of the FFT pupil within its square canvas. Also sets the scale of the shared ghost aperture mask."; ui_type="slider"; ui_min=0.05; ui_max=0.98;  > = 0.82;
uniform float ApertureAspect < ui_category="06. Shared pupil size and shape";  ui_label="Aperture aspect ratio"; ui_tooltip="Stretch the pupil horizontally while shrinking it vertically. Diffraction stretches in the opposite direction."; ui_type="slider"; ui_min=0.25; ui_max=4;  > = 1;
uniform int BladeCount < ui_category="06. Shared pupil size and shape";  ui_label="Blade count"; ui_tooltip="Number of iris blades forming the procedural opening."; ui_type="slider"; ui_min=3; ui_max=16;  > = 6;
uniform float BladeRotation < ui_category="06. Shared pupil size and shape";  ui_label="Blade rotation"; ui_tooltip="Rotate the procedural iris and its diffraction pattern."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform float BladeRoundness < ui_category="06. Shared pupil size and shape";  ui_label="Blade roundness"; ui_tooltip="Blend the polygonal opening towards a circle."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0.15;
uniform float CornerRounding < ui_category="06. Shared pupil size and shape";  ui_label="Blade corner rounding"; ui_tooltip="Round polygon corners while retaining straight blade edges."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float EdgeSoftness < ui_category="06. Shared pupil size and shape";  ui_label="Edge softness"; ui_tooltip="Width of the transition between transmitting and blocked pupil areas."; ui_type="slider"; ui_min=0; ui_max=0.1;  > = 0.002;

// 07. Custom pupil PNG
uniform bool UseCustomAperture < ui_category="07. Custom pupil PNG";  ui_label="Use custom aperture PNG"; ui_tooltip="Use the PNG as the pupil opening. PNG loading must be enabled in the effect definitions.";  ui_category_closed=true; > = false;
uniform int CustomChannel < ui_category="07. Custom pupil PNG";  ui_label="PNG mask channel"; ui_tooltip="Read mask values from RGB luminance, transparency, or the red channel."; ui_type="combo"; ui_items="Luminance\0Alpha\0Red\0";  > = 0;
uniform bool CustomCombine < ui_category="07. Custom pupil PNG";  ui_label="Keep procedural opening"; ui_tooltip="Multiply the PNG by the procedural iris instead of replacing the iris outline.";  > = false;
uniform bool CustomIntensity < ui_category="07. Custom pupil PNG";  ui_label="PNG represents intensity"; ui_tooltip="Treat PNG values as light intensity and convert them to pupil amplitude.";  > = false;
uniform bool CustomInvert < ui_category="07. Custom pupil PNG";  ui_label="Invert PNG mask"; ui_tooltip="Swap transmitting and blocked values inside the PNG canvas.";  > = false;
uniform float CustomGamma < ui_category="07. Custom pupil PNG";  ui_label="PNG mask curve"; ui_tooltip="Power curve for PNG transmission. 1 retains the image's numeric values."; ui_type="slider"; ui_min=0.1; ui_max=4;  > = 1;
uniform float2 CustomScale < ui_category="07. Custom pupil PNG";  ui_label="PNG scale X / Y"; ui_tooltip="Scale the PNG horizontally and vertically relative to the pupil opening."; ui_type="slider"; ui_min=0.1; ui_max=4;  > = float2(1,1);
uniform float2 CustomOffset < ui_category="07. Custom pupil PNG";  ui_label="PNG offset X / Y"; ui_tooltip="Move the PNG within the pupil. A simple translation does not change in-focus diffraction intensity."; ui_type="slider"; ui_min=-1; ui_max=1;  > = float2(0,0);
uniform float CustomRotation < ui_category="07. Custom pupil PNG";  ui_label="PNG rotation"; ui_tooltip="Rotate the PNG within the pupil."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;

// 08. Pupil clipping and fade
uniform float Obstruction < ui_category="08. Pupil clipping and fade";  ui_label="Central obstruction"; ui_tooltip="Radius of a blocked disc at the centre of the pupil."; ui_type="slider"; ui_min=0; ui_max=0.85;  ui_category_closed=true; > = 0;
uniform int StrutCount < ui_category="08. Pupil clipping and fade";  ui_label="Support strut count"; ui_tooltip="Number of support spokes crossing the pupil. 0 removes them."; ui_type="slider"; ui_min=0; ui_max=12;  > = 0;
uniform float StrutWidth < ui_category="08. Pupil clipping and fade";  ui_label="Strut width"; ui_tooltip="Half-width of each support spoke relative to the opening radius."; ui_type="slider"; ui_min=0; ui_max=0.1;  > = 0.012;
uniform float StrutRotation < ui_category="08. Pupil clipping and fade";  ui_label="Strut rotation"; ui_tooltip="Rotate the support spokes and their diffraction lines."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform float CatEye < ui_category="08. Pupil clipping and fade";  ui_label="Cat-eye clipping"; ui_tooltip="Clip one side of the pupil to form a cat-eye opening."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float CatEyeAngle < ui_category="08. Pupil clipping and fade";  ui_label="Cat-eye direction"; ui_tooltip="Direction of cat-eye clipping around the pupil."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform float Apodization < ui_category="08. Pupil clipping and fade";  ui_label="Radial transmission fade"; ui_tooltip="Fade pupil transmission towards the rim, reducing hard-edge diffraction."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float ApodizationFalloff < ui_category="08. Pupil clipping and fade";  ui_label="Radial fade curve"; ui_tooltip="Shape of the radial fade. Higher values concentrate it near the rim."; ui_type="slider"; ui_min=0.5; ui_max=8;  > = 2;

// 09. Iris edge irregularity
uniform float BladeNoiseAmount < ui_category="09. Iris edge irregularity";  ui_label="Blade edge noise"; ui_tooltip="Amount of irregularity along the procedural blade edges."; ui_type="slider"; ui_min=0; ui_max=0.3;  ui_category_closed=true; > = 0;
uniform float BladeNoiseFrequency < ui_category="09. Iris edge irregularity";  ui_label="Blade noise detail"; ui_tooltip="Number of fine variations along the noisy iris edge."; ui_type="slider"; ui_min=1; ui_max=128;  > = 16;
uniform float BladeNoiseRoughness < ui_category="09. Iris edge irregularity";  ui_label="Blade noise roughness"; ui_tooltip="Amount of finer detail added to blade-edge noise."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0.5;
uniform int BladeNoiseSeed < ui_category="09. Iris edge irregularity";  ui_label="Blade noise seed"; ui_tooltip="Choose a repeatable blade-edge noise pattern."; ui_type="slider"; ui_min=0; ui_max=65535;  > = 0;

// 10. Pupil dust and scratches
uniform float DustOpacity < ui_category="10. Pupil dust and scratches";  ui_label="Dust opacity"; ui_tooltip="How strongly dust blocks light through the pupil."; ui_type="slider"; ui_min=0; ui_max=1;  ui_category_closed=true; > = 0;
uniform float DustCoverage < ui_category="10. Pupil dust and scratches";  ui_label="Dust coverage"; ui_tooltip="Density of dust particles. Requires dust opacity above 0."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0.35;
uniform float DustSize < ui_category="10. Pupil dust and scratches";  ui_label="Dust size (% of opening)"; ui_tooltip="Typical dust diameter as a percentage of the opening diameter."; ui_type="slider"; ui_min=0.05; ui_max=10;  > = 1.5;
uniform float ScratchOpacity < ui_category="10. Pupil dust and scratches";  ui_label="Scratch opacity"; ui_tooltip="How strongly scratches block light through the pupil."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform int ScratchCount < ui_category="10. Pupil dust and scratches";  ui_label="Scratch count"; ui_tooltip="Number of scratch segments distributed across the pupil."; ui_type="slider"; ui_min=0; ui_max=32;  > = 6;
uniform float ScratchWidth < ui_category="10. Pupil dust and scratches";  ui_label="Scratch width (% of opening)"; ui_tooltip="Typical scratch width as a percentage of the opening diameter."; ui_type="slider"; ui_min=0.02; ui_max=2;  > = 0.2;
uniform float ScratchLength < ui_category="10. Pupil dust and scratches";  ui_label="Scratch length (% of opening)"; ui_tooltip="Typical scratch length as a percentage of the opening diameter."; ui_type="slider"; ui_min=1; ui_max=150;  > = 60;
uniform float ScratchAngle < ui_category="10. Pupil dust and scratches";  ui_label="Scratch direction"; ui_tooltip="Main direction of scratches. Their diffraction streaks run approximately perpendicular to them."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform float ScratchSpread < ui_category="10. Pupil dust and scratches";  ui_label="Scratch direction variation"; ui_tooltip="Random variation around the main scratch direction."; ui_type="slider"; ui_min=0; ui_max=180;  > = 45;
uniform float TransmissionVariation < ui_category="10. Pupil dust and scratches";  ui_label="Uneven transmission"; ui_tooltip="Strength of broad patches of reduced pupil transmission."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float TransmissionSize < ui_category="10. Pupil dust and scratches";  ui_label="Transmission patch size (%)"; ui_tooltip="Size of the uneven-transmission patches relative to the opening diameter."; ui_type="slider"; ui_min=2; ui_max=100;  > = 25;
uniform int ImperfectionSeed < ui_category="10. Pupil dust and scratches";  ui_label="Imperfection seed"; ui_tooltip="Choose a repeatable dust, scratch and transmission pattern."; ui_type="slider"; ui_min=0; ui_max=65535;  > = 0;

// 11. Sampling and convergence
}
uniform int RayBudget < ui_category="11. Sampling and convergence";  ui_label="Pupil samples per frame"; ui_type="slider"; ui_min=1024; ui_max=262144; ui_step=1024; ui_tooltip="Pupil samples traced per frame, shared across sources and reflection sequences."; ui_category_closed=true; > = 131072;
uniform int SpectralSamples < ui_category="11. Sampling and convergence";  ui_label="Spectral samples"; ui_type="slider"; ui_min=1; ui_max=17; ui_step=1; ui_tooltip="Wavelengths traced per pupil sample. More samples smooth spectral colour variation and increase work."; > = RTL_SPECTRAL_SAMPLES;
uniform bool UseBounds < ui_category="11. Sampling and convergence";  ui_label="Tight entrance bounds"; ui_tooltip="Sample each reflection sequence inside its cached entrance box."; > = true;
uniform float BoundsPadding < ui_category="11. Sampling and convergence";  ui_label="Bounds padding (probe cells)"; ui_type="slider"; ui_min=0; ui_max=8; ui_step=0.1; ui_tooltip="Margin around pilot-ray bounds, measured in probe cells."; > = 2;
uniform bool BrightnessBudget < ui_category="11. Sampling and convergence";  ui_label="Allocate by ghost energy per angle"; ui_tooltip="Give more samples to reflection sequences carrying more energy at each source angle."; > = true;
uniform float BudgetExponent < ui_category="11. Sampling and convergence";  ui_label="Brightness budget exponent"; ui_type="slider"; ui_min=0; ui_max=2; ui_step=0.01; ui_tooltip="How strongly sequence brightness influences sampling. 0 gives equal weights."; > = 0.75;
uniform float UniformBudgetFraction < ui_category="11. Sampling and convergence";  ui_label="Uniform sampling fraction"; ui_type="slider"; ui_min=0; ui_max=1; ui_step=0.001; ui_tooltip="Fraction of the sequence budget distributed equally, retaining samples for weak ghosts."; > = 0.03;
uniform float SplatRadius < ui_category="11. Sampling and convergence";  ui_label="Ray tent radius (flare pixels)"; ui_type="slider"; ui_min=0.5; ui_max=4; ui_step=0.05; ui_tooltip="Radius of the normalized tent used to deposit each sensor hit, in ghost-buffer pixels."; > = 1.25;
uniform float FixedPointScale < ui_category="11. Sampling and convergence";  ui_label="Atomic fixed-point scale"; ui_type="slider"; ui_min=1024; ui_max=1048576; ui_step=1024; ui_tooltip="Precision of integer photon accumulation. Higher values retain weaker contributions but reduce overflow headroom."; > = 1048576;
uniform bool FreezeNoise < ui_category="11. Sampling and convergence";  ui_label="Freeze sample pattern"; ui_tooltip="Reuse the same samples each frame. Useful for comparisons; repeated frames add no new samples."; > = false;
uniform int NoiseSeed < ui_category="11. Sampling and convergence";  ui_label="Sampling seed"; ui_type="slider"; ui_min=0; ui_max=65535; ui_step=1; ui_tooltip="Choose a repeatable ray-sampling pattern."; > = 1;
uniform float TemporalWeight < ui_category="11. Sampling and convergence";  ui_label="Temporal history weight"; ui_type="slider"; ui_min=0; ui_max=0.99; ui_step=0.01; ui_tooltip="Fraction of the previous ghost image retained each frame. Higher values reduce noise but respond more slowly."; > = 0.65;
uniform bool Progressive < ui_category="11. Sampling and convergence";  ui_label="Progressive stationary accumulation"; ui_tooltip="Average all stationary frames equally. Lens or source changes restart accumulation."; > = false;
uniform float MotionTolerance < ui_category="11. Sampling and convergence";  ui_label="Source movement tolerance (UV)"; ui_type="slider"; ui_min=0; ui_max=0.05; ui_step=0.0001; ui_tooltip="Source-position change allowed before ghost history is discarded, in normalized image coordinates."; > = 0.002;

// 12. Preview filtering
uniform bool DenoiseEnabled < ui_category="12. Preview filtering";  ui_label="Preview denoising"; ui_tooltip="Filter the displayed ghost image for a cleaner low-sample preview. Raw accumulation stays unchanged."; ui_category_closed=true; > = false;
uniform int DenoiseMethod < ui_category="12. Preview filtering";  ui_label="Preview denoise method"; ui_type="combo"; ui_items="Adaptive wavelet\0Local filter\0";  ui_tooltip="Adaptive wavelet filters noise at four spatial scales. Local filter retains the original single-pass method."; > = 0;
uniform float DenoiseStrength < ui_category="12. Preview filtering";  ui_label="Preview denoise strength"; ui_tooltip="Blend between raw and filtered ghosts. Progressive filtering fades as independent frames accumulate."; ui_type="slider"; ui_min=0; ui_max=1; > = 0.75;
uniform int DenoiseRadius < ui_category="12. Preview filtering";  ui_label="Preview denoise radius"; ui_tooltip="Neighbourhood radius in ghost-buffer pixels. The adaptive method expands this radius across four scales."; ui_type="slider"; ui_min=1; ui_max=4; > = 2;
uniform float DenoiseEdge < ui_category="12. Preview filtering";  ui_label="Preview edge preservation"; ui_tooltip="Sensitivity to colour and brightness edges. Higher values keep sharp ghost boundaries more strongly."; ui_type="slider"; ui_min=0; ui_max=8; > = 4;
uniform float DenoiseNoise < ui_category="12. Preview filtering";  ui_label="Preview noise tolerance"; ui_type="slider"; ui_min=0; ui_max=8; ui_step=0.05;  ui_tooltip="Noise tolerance of the adaptive filter. Higher values smooth more strongly; lower values retain more detail."; > = 2;

// 13. Ghost and bloom appearance
uniform float FlareExposure < ui_category="13. Ghost and bloom appearance";  ui_label="Ghost exposure (stops)"; ui_type="slider"; ui_min=-8; ui_max=16; ui_step=0.1; ui_tooltip="Exposure of the traced ghost image, in stops."; ui_category_closed=true; > = 7;
uniform float3 FlareTint < ui_category="13. Ghost and bloom appearance";  ui_label="Ghost tint"; ui_type="slider"; ui_min=0; ui_max=4; ui_step=0.01; ui_tooltip="Colour multiplier applied to displayed ghosts."; > = float3(1,1,1);
uniform float FlareSaturation < ui_category="13. Ghost and bloom appearance";  ui_label="Ghost saturation"; ui_type="slider"; ui_min=0; ui_max=3; ui_step=0.01; ui_tooltip="Colour saturation of displayed ghosts. 0 makes them monochrome."; > = 1;
uniform bool BloomEnabled < ui_category="13. Ghost and bloom appearance";  ui_label="FFT diffraction / bloom"; ui_tooltip="Enable FFT diffraction and bloom from the selected sources."; > = true;
uniform bool FFTAfterGhosts < ui_category="13. Ghost and bloom appearance";  ui_label="FFT after ghosts"; ui_tooltip="Include resolved ghosts in the FFT input. Off applies FFT to scene sources before adding ghosts."; > = true;
uniform float GhostDiffraction < ui_category="13. Ghost and bloom appearance";  ui_label="Convolve ghosts with FFT kernel"; ui_type="slider"; ui_min=0; ui_max=1; ui_step=0.01; ui_tooltip="Amount of the ghost image convolved with the FFT kernel. Used when FFT after ghosts is enabled."; > = 0.15;
namespace FFT {
uniform float BloomIntensity < ui_category="13. Ghost and bloom appearance";  ui_label="Bloom intensity"; ui_tooltip="Brightness multiplier for the final FFT bloom."; ui_type="slider"; ui_min=0; ui_max=4;  > = 0.35;
uniform float3 BloomTint < ui_category="13. Ghost and bloom appearance";  ui_label="Bloom tint"; ui_tooltip="Colour multiplier for the final FFT bloom."; ui_type="slider"; ui_min=0; ui_max=2;  > = float3(1,1,1);
uniform float BloomSaturation < ui_category="13. Ghost and bloom appearance";  ui_label="Bloom saturation"; ui_tooltip="Colour saturation of the final FFT bloom."; ui_type="slider"; ui_min=0; ui_max=2;  > = 1;

// 14. Diffraction kernel
uniform float KernelScale < ui_category="14. Diffraction kernel";  ui_label="PSF scale (display pixels)"; ui_tooltip="Scale the PSF in display pixels. Larger values spread light farther."; ui_type="slider"; ui_min=0.25; ui_max=32;  ui_category_closed=true; > = 1;
uniform float Anamorphism < ui_category="14. Diffraction kernel";  ui_label="Anamorphic stretch"; ui_tooltip="Additional horizontal stretch of the PSF."; ui_type="slider"; ui_min=0.125; ui_max=8;  > = 1;
uniform float2 KernelStretch < ui_category="14. Diffraction kernel";  ui_label="Kernel stretch X / Y"; ui_tooltip="Independent horizontal and vertical PSF scale multipliers."; ui_type="slider"; ui_min=0.125; ui_max=8;  > = float2(1,1);
uniform float KernelRotation < ui_category="14. Diffraction kernel";  ui_label="Bloom rotation"; ui_tooltip="Rotate the PSF around its centre."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform int Normalization < ui_category="14. Diffraction kernel";  ui_label="Kernel output"; ui_tooltip="Choose raw, total-energy, or peak-normalized FFT kernel output."; ui_type="combo"; ui_items="Raw / unnormalised\0Unit energy\0Unit peak\0";  > = 0;
uniform float KernelExposure < ui_category="14. Diffraction kernel";  ui_label="PSF exposure (stops)"; ui_tooltip="Exposure of the PSF before final bloom intensity."; ui_type="slider"; ui_min=-12; ui_max=12;  > = 0;
uniform float KernelEdgeFade < ui_category="14. Diffraction kernel";  ui_label="Kernel edge fade"; ui_tooltip="Fade the PSF near its canvas edge to soften truncation."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;
uniform float DiffractionStrength < ui_category="14. Diffraction kernel";  ui_label="Diffraction strength"; ui_tooltip="Brightness of directional diffraction spikes relative to the bloom core and wings."; ui_type="slider"; ui_min=0; ui_max=16;  > = 2;
uniform float DiffractionExposure < ui_category="14. Diffraction kernel";  ui_label="Diffraction exposure (stops)"; ui_tooltip="Exposure of diffraction relative to the core and wings."; ui_type="slider"; ui_min=-8; ui_max=16;  > = 2;
uniform float CoreIntensity < ui_category="14. Diffraction kernel";  ui_label="Core intensity"; ui_tooltip="Weight of the compact bloom core."; ui_type="slider"; ui_min=0; ui_max=4;  > = 0.3;
uniform float WingIntensity < ui_category="14. Diffraction kernel";  ui_label="Wing intensity"; ui_tooltip="Weight of the broad diffraction wings."; ui_type="slider"; ui_min=0; ui_max=8;  > = 1;
uniform float WingLift < ui_category="14. Diffraction kernel";  ui_label="Wing lift"; ui_tooltip="Lift faint diffraction wings before combining the kernel components."; ui_type="slider"; ui_min=0; ui_max=0.75;  > = 0;
uniform float SpectralDispersion < ui_category="14. Diffraction kernel";  ui_label="Spectral dispersion"; ui_tooltip="Scale the wavelength-dependent size of diffraction."; ui_type="slider"; ui_min=0; ui_max=4;  > = 1;
uniform float ChromaticFocus < ui_category="14. Diffraction kernel";  ui_label="Chromatic focal shift"; ui_tooltip="Change pupil defocus with wavelength."; ui_type="slider"; ui_min=-4; ui_max=4;  > = 0;
uniform float FringeSuppression < ui_category="14. Diffraction kernel";  ui_label="Chromatic fringe suppression"; ui_tooltip="Blend spectral kernel colours towards neutral to reduce coloured fringes."; ui_type="slider"; ui_min=0; ui_max=1;  > = 0;

// 15. Wavefront aberrations
uniform float Defocus < ui_category="15. Wavefront aberrations";  ui_label="Defocus (signed waves)"; ui_tooltip="Signed pupil defocus in waves. Either sign moves the PSF away from best focus."; ui_type="slider"; ui_min=-8; ui_max=8;  ui_category_closed=true; > = 0;
uniform float Astigmatism < ui_category="15. Wavefront aberrations";  ui_label="Astigmatism (waves)"; ui_tooltip="Difference in focus between perpendicular pupil directions, in waves."; ui_type="slider"; ui_min=-8; ui_max=8;  > = 0;
uniform float AstigmatismAngle < ui_category="15. Wavefront aberrations";  ui_label="Astigmatism angle"; ui_tooltip="Orientation of the astigmatism axes."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform float Spherical < ui_category="15. Wavefront aberrations";  ui_label="Spherical aberration"; ui_tooltip="Radially varying wavefront error from spherical aberration."; ui_type="slider"; ui_min=-4; ui_max=4;  > = 0;
uniform float Coma < ui_category="15. Wavefront aberrations";  ui_label="Coma"; ui_tooltip="Asymmetric wavefront error that produces a comet-like PSF."; ui_type="slider"; ui_min=-4; ui_max=4;  > = 0;
uniform float ComaAngle < ui_category="15. Wavefront aberrations";  ui_label="Coma angle"; ui_tooltip="Direction of coma."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;
uniform float Trefoil < ui_category="15. Wavefront aberrations";  ui_label="Trefoil"; ui_tooltip="Three-lobed wavefront error."; ui_type="slider"; ui_min=-4; ui_max=4;  > = 0;
uniform float TrefoilAngle < ui_category="15. Wavefront aberrations";  ui_label="Trefoil angle"; ui_tooltip="Orientation of the trefoil pattern."; ui_type="slider"; ui_min=-180; ui_max=180;  > = 0;

// 16. Fresnel propagation
uniform bool FresnelEnabled < ui_category="16. Fresnel propagation";  ui_label="Fresnel propagation"; ui_tooltip="Propagate the complex pupil over a finite distance instead of using far-field diffraction.";  ui_category_closed=true; > = false;
uniform bool FresnelLens < ui_category="16. Fresnel propagation";  ui_label="Include focusing lens"; ui_tooltip="Include the quadratic phase of a focusing lens in Fresnel propagation.";  > = true;
uniform float FresnelCanvasMM < ui_category="16. Fresnel propagation";  ui_label="Pupil canvas width (mm)"; ui_tooltip="Physical width of the pupil canvas used for Fresnel calculations."; ui_type="slider"; ui_min=0.05; ui_max=20;  > = 1;
uniform float FresnelDistanceMM < ui_category="16. Fresnel propagation";  ui_label="Propagation distance (mm)"; ui_tooltip="Distance from the pupil to the observation plane."; ui_type="slider"; ui_min=1; ui_max=5000;  > = 50;
uniform float FresnelFocalMM < ui_category="16. Fresnel propagation";  ui_label="Lens focal length (mm)"; ui_tooltip="Focal length of the Fresnel focusing lens."; ui_type="slider"; ui_min=1; ui_max=1000;  > = 50;
uniform float FresnelPixelUM < ui_category="16. Fresnel propagation";  ui_label="Observation pixel pitch (um)"; ui_tooltip="Physical observation-pixel pitch in micrometres."; ui_type="slider"; ui_min=0.1; ui_max=50;  > = 2;
uniform bool FresnelUnshaped < ui_category="16. Fresnel propagation";  ui_label="Unshaped Fresnel PSF"; ui_tooltip="Use the raw Fresnel intensity without the artistic core and wing shaping.";  > = true;

// 17. Diagnostics and optical paths
}
uniform int RTDebugView < ui_category="17. Diagnostics and optical paths";  ui_type="combo"; ui_items="Composite\0Ghosts only\0FFT only\0Extracted source\0Detected lights\0Pupil and FFT kernel\0Entrance bounds\0Ghost budget by angle\0Ray counters\0Lens geometry and ray paths\0"; ui_tooltip="Inspect sources, optics, budgets or lens paths. Lens view: amber direct rays, cyan reflections, red blocked paths."; ui_category_closed=true; > = 0;
uniform int InspectSequence < ui_category="17. Diagnostics and optical paths";  ui_label="Bounds sequence"; ui_type="slider"; ui_min=0; ui_max=_RTL_GHOSTS-1; ui_step=1; ui_tooltip="Reflection sequence shown in the bounds and lens-path views."; > = 10;
uniform int InspectAngle < ui_category="17. Diagnostics and optical paths";  ui_label="Bounds angle bin"; ui_type="slider"; ui_min=0; ui_max=RTL_ANGLE_BINS-1; ui_step=1; ui_tooltip="Polar incidence-angle bin shown in the cached-bounds views."; > = 10;
uniform int InspectAzimuth < ui_category="17. Diagnostics and optical paths";  ui_label="Bounds azimuth bin"; ui_type="slider"; ui_min=0; ui_max=RTL_AZIMUTH_BINS-1; ui_step=1; ui_tooltip="Azimuth bin shown in anamorphic bounds and sequence budgets."; > = 0;
uniform float DiagramPlane < ui_category="17. Diagnostics and optical paths";  ui_label="Lens section angle (degrees)"; ui_tooltip="Cross-section direction around the lens axis. 0 shows X/Z; 90 shows Y/Z."; ui_type="slider"; ui_min=0; ui_max=180; > = 0;
uniform float DiagramAngle < ui_category="17. Diagnostics and optical paths";  ui_label="Diagram incident angle (degrees)"; ui_tooltip="Incident ray angle within the selected lens cross-section."; ui_type="slider"; ui_min=-60; ui_max=60; > = 0;
uniform int DiagramRays < ui_category="17. Diagnostics and optical paths";  ui_label="Diagram ray count"; ui_tooltip="Number of entrance rays drawn for the direct and selected reflected paths."; ui_type="slider"; ui_min=1; ui_max=65; > = 17;
uniform float DiagramWavelength < ui_category="17. Diagnostics and optical paths";  ui_label="Diagram wavelength (nm)"; ui_tooltip="Wavelength used to draw refracted and reflected paths, in nanometres."; ui_type="slider"; ui_min=420; ui_max=680; > = 550;
uniform int SequenceOnly < ui_category="17. Diagnostics and optical paths";  ui_label="Sequence isolation (-1 = all)"; ui_type="slider"; ui_min=-1; ui_max=_RTL_GHOSTS-1; ui_step=1; ui_tooltip="Trace one reflection sequence. -1 includes all sequences."; > = -1;
uniform bool RTForceRebuild < ui_category="17. Diagnostics and optical paths";  ui_label="Rebuild bounds each frame";  ui_tooltip="Rebuild optical bounds every frame, even when the lens is unchanged."; > = false;

// 18. Optics preview display
namespace FFT {
uniform float PreviewExposure < ui_category="18. Optics preview display";  ui_label="Kernel preview exposure"; ui_tooltip="Exposure of the displayed PSF preview."; ui_type="slider"; ui_min=-12; ui_max=20;  ui_category_closed=true; > = 7;
uniform bool PreviewLog < ui_category="18. Optics preview display";  ui_label="Log kernel preview"; ui_tooltip="Use a logarithmic PSF preview so faint diffraction is visible.";  > = true;
uniform bool PreviewNative < ui_category="18. Optics preview display";  ui_label="Display kernel at native pixel size"; ui_tooltip="Show one kernel texel per display pixel instead of fitting it to the preview square.";  > = true;
uniform float PreviewZoom < ui_category="18. Optics preview display";  ui_label="Kernel preview zoom"; ui_tooltip="Magnification of the native-size kernel preview."; ui_type="slider"; ui_min=0.1; ui_max=8;  > = 1;

// 19. Test light
}
uniform bool TestLight < ui_category="19. Test light";  ui_label="Override with test light"; ui_tooltip="Replace frame sources with a single controllable point light."; ui_category_closed=true; > = false;
uniform float2 TestPosition < ui_category="19. Test light";  ui_label="Test light position (UV)"; ui_type="slider"; ui_min=-0.5; ui_max=1.5; ui_step=0.001; ui_tooltip="Point-light position in normalized image coordinates. Values outside the frame are supported."; > = float2(0.8,0.25);
uniform float3 TestColour < ui_category="19. Test light";  ui_label="Test light linear RGB"; ui_type="slider"; ui_min=0; ui_max=4; ui_step=0.01; ui_tooltip="Linear RGB colour of the test light."; > = float3(1,1,1);
uniform float TestPower < ui_category="19. Test light";  ui_label="Test light pixel flux"; ui_type="slider"; ui_min=0; ui_max=1000; ui_step=1; ui_tooltip="Total pixel flux of the test light."; > = 100;

// Original hidden controls and runtime-provided uniforms.
namespace FFT {
uniform int BlendMode <  hidden=true; ui_category="FFT / Bloom"; ui_label="Blend"; ui_tooltip="Additive adds glow directly. Screen reduces the addition near white. Energy redistribution removes some extracted light before spreading it into bloom."; ui_type="combo"; ui_items="Additive\0Screen\0Energy redistribution\0";  > = 0;
uniform int DebugView <  hidden=true; ui_category="FFT / Bloom"; ui_label="View"; ui_tooltip="Composite shows the scene with bloom. Highlights shows extracted light. Bloom shows the finished glow. Aperture + kernel shows the lens opening and its light-spread pattern in square previews."; ui_type="combo"; ui_items="Composite\0Highlights\0Bloom\0Aperture + kernel\0";  > = 0;
uniform bool OutputClamp <  hidden=true; ui_category="FFT / Colour space"; ui_label="Clamp SDR output"; ui_tooltip="Limits the final sRGB SDR output to the 0-1 range. Automatically ignored for Linear / scRGB and HDR10 PQ.";  > = true;
uniform int FrameCount <  source="framecount"; >;
uniform float FrameTime <  source="frametime"; >;
uniform bool ForceRebuild <  source="key"; keycode=0x75; mode="press"; >;
}
